arm_shoulder_pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm_shoulder_pan_joint
    joint_speed: 2.0
    motor:
        id: 1
        init: 1023
        min: 0
        max: 2048

